const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const panel=$("#panel"),last=$("#lastGame"),cont=$("#continueBtn");
const load=()=>{try{return JSON.parse(localStorage.getItem("pontinhoGame")||"null")}catch{return null}};
const save=g=>{localStorage.setItem("pontinhoGame",JSON.stringify(g));renderHome();window.dispatchEvent(new Event("pontinho:updated"))};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(msg){const t=document.createElement("div");t.className="toast";t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)}
function renderHome(){const g=load();if(!g){last.innerHTML="Nenhuma partida em andamento.";cont.classList.add("hidden");return}last.innerHTML=`<strong>${esc(g.name)}</strong><br><span class="muted">Rodada ${g.round} • limite ${g.limit} • ${g.players.length} jogadores</span>`;cont.classList.remove("hidden")}
function show(html){panel.innerHTML=html;panel.classList.remove("hidden");panel.scrollIntoView({behavior:"smooth",block:"start"})}
function closePanel(){panel.classList.add("hidden")}
function newGame(){show(`<div class="panel-title"><h2>Nova partida</h2></div><div class="field"><label>Nome da partida</label><input id="gameName" placeholder="Ex.: Domingo em família"></div><div class="field"><label>Limite de pontos</label><input id="limit" type="number" min="1" value="100"></div><div class="field"><label class="toggle-line"><span>Permitir recompra</span><input id="allowRebuy" type="checkbox" checked></label></div><div class="field"><label>Jogadores</label><div id="players"></div><button id="addPlayer" class="secondary">+ Adicionar jogador</button></div><div class="actions-row"><button id="cancel" class="secondary">Cancelar</button><button id="start" class="primary">Iniciar partida</button></div>`);
const box=$("#players");addPlayer();addPlayer();$("#addPlayer").onclick=addPlayer;
function addPlayer(){const row=document.createElement("div");row.className="player-input";row.innerHTML='<input class="pname" placeholder="Nome do jogador"><button class="secondary remove">×</button>';row.querySelector(".remove").onclick=()=>row.remove();box.appendChild(row)}
$("#cancel").onclick=closePanel;$("#start").onclick=()=>{const names=$$(".pname").map(x=>x.value.trim()).filter(Boolean);if(names.length<2){alert("Adicione pelo menos 2 jogadores.");return}const g={name:$("#gameName").value.trim()||"Partida de Pontinho",limit:Math.max(1,+$("#limit").value||100),round:0,allowRebuy:$("#allowRebuy").checked,players:names.map(name=>({name,score:0,eliminated:false,eliminatedRound:null,rebuys:0})),rounds:[]};save(g);showGame();toast("Partida criada")}}
function showGame(){const g=load();if(!g)return;const sorted=g.players.map((p,i)=>({...p,i})).sort((a,b)=>a.score-b.score);const active=sorted.filter(p=>!p.eliminated);show(`<div class="panel-title"><div><h2>${esc(g.name)}</h2><span class="muted">Rodada ${g.round} • limite ${g.limit}</span></div>${active.length>1?'<button id="newRound" class="primary">+ Nova rodada</button>':'<button id="finish" class="primary">Finalizar</button>'}</div><div>${sorted.map((p,pos)=>`<div class="score-row"><div><b>${pos+1}. ${esc(p.name)}</b>${p.eliminated?'<span class="badge">ESTOUROU</span>':''}</div><div class="score ${p.eliminated?'red':p.score>=g.limit*.8?'yellow':'green'}">${p.score}</div><div class="place">${p.eliminated?(g.allowRebuy&&active.length>1?`<button class="secondary small rebuy" data-i="${p.i}">Recomprar</button>`:"—"):"ativo"}</div></div>`).join("")}</div>${g.allowRebuy&&active.length>1&&sorted.some(p=>p.eliminated)?'<p class="muted">Jogadores que estouraram podem usar <b>Recomprar</b> para voltar à partida.</p>':""}<div class="actions-row"><button id="homeClose" class="secondary">Fechar</button>${g.rounds.length?'<button id="undo" class="secondary">↩ Desfazer</button>':""}</div>`);
if($("#newRound"))$("#newRound").addEventListener("click",function(e){e.preventDefault();showRound(null)});$$(".rebuy").forEach(b=>b.onclick=()=>showRebuyPrompt(+b.dataset.i));if($("#finish"))$("#finish").addEventListener("click",function(e){e.preventDefault();finishGame()});$("#homeClose").onclick=closePanel;if($("#undo"))$("#undo").onclick=undoRound}
function showRound(editIndex=null){const g=load();const previous=editIndex===null?null:g.rounds[editIndex];const basePlayers=editIndex===null?g.players.map(p=>({...p})):previous.beforePlayers.map(p=>({...p}));
const active=basePlayers.map((p,i)=>({...p,i})).filter(p=>!p.eliminated);
show(`<div class="panel-title"><div><h2>${editIndex===null?"Rodada "+(g.round+1):"Editar rodada "+previous.round}</h2><span class="muted">Preencha os pontos e confira antes de salvar.</span></div></div>
<div class="round-layout">
<section class="round-section"><h3>Quem bateu?</h3><div id="winnerGrid" class="winner-grid">${active.map(p=>`<button class="winner" data-i="${p.i}">${esc(p.name)}</button>`).join("")}</div><p class="keyhint">Quem bater recebe automaticamente 0 pontos.</p></section>
<section class="round-section"><h3>Pontos que ficaram na mão</h3><div id="pointsGrid" class="points-grid">${active.map(p=>`<div class="point-row"><span class="point-name ${previous&&previous.winner===p.i?'locked':''}">${esc(p.name)}</span><input class="points" data-i="${p.i}" type="number" min="0" inputmode="numeric" autocomplete="off" value="${previous?previous.points[p.i]||0:""}" placeholder="0"></div>`).join("")}</div></section>
</div>
<div class="actions-row"><button id="cancelRound" class="secondary">Cancelar</button><button id="saveRound" class="primary">${editIndex===null?"Salvar rodada":"Salvar alteração"}</button></div>`);

let winner=previous?previous.winner:null;
const winnerButtons=$$(".winner"), pointInputs=$$(".points");

winnerButtons.forEach(b=>{if(+b.dataset.i===winner)b.classList.add("selected");b.onclick=()=>{winner=+b.dataset.i;winnerButtons.forEach(x=>x.classList.toggle("selected",x===b));update();focusFirstPoint()}});
function update(){pointInputs.forEach(x=>{const i=+x.dataset.i;x.disabled=winner===i;x.classList.toggle("locked",winner===i);if(winner===i)x.value=0})}
function focusFirstPoint(){const first=pointInputs.find(x=>!x.disabled);if(first){first.focus();first.select()}}
pointInputs.forEach((x,index)=>{x.oninput=update;x.onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();const next=pointInputs.slice(index+1).find(y=>!y.disabled);if(next){next.focus();next.select()}else{$("#saveRound").focus()}}}});
$("#cancelRound").onclick=showGame;
$("#saveRound").onclick=()=>{if(winner===null){alert("Escolha quem bateu.");return}const points={};pointInputs.forEach(x=>points[x.dataset.i]=+x.value||0);
if(editIndex!==null){const r=g.rounds[editIndex];const rebuilt=g.rounds.slice(0,editIndex).reduce((players,round)=>applyRound(players,round),g.rounds[0]?.beforePlayers?.map(p=>({...p,score:0,eliminated:false}))||basePlayers.map(p=>({...p,score:0,eliminated:false})));const next=applyRound(rebuilt,{winner,points});g.rounds[editIndex]={...r,winner,points};g.players=next;for(let i=editIndex+1;i<g.rounds.length;i++)g.players=applyRound(g.players,g.rounds[i]);save(g);showGame();toast("Rodada corrigida");return}
const before=g.players.map(p=>({...p}));g.round++;g.players=applyRound(g.players,{winner,points});g.players.forEach((p,i)=>{const was=before[i]?.eliminated===true;if(!was&&p.eliminated)p.eliminatedRound=g.round;});g.rounds.push({round:g.round,winner,points,beforePlayers:before});save(g);const activeAfter=g.players.filter(p=>!p.eliminated);if(activeAfter.length<=1){finishGame();toast("Partida encerrada")}else{showGame();toast("Rodada salva")}};
update();if(winner!==null)focusFirstPoint();else if(winnerButtons[0])winnerButtons[0].focus()}
function showRebuyPrompt(playerIndex){const g=load();const p=g.players[playerIndex];if(!p||!p.eliminated||!g.allowRebuy){showGame();return}
const active=g.players.filter(x=>!x.eliminated&&x!==p);const highest=active.length?Math.max(...active.map(x=>x.score)):0;
show(`<div class="rebuy-box"><h3>🔴 ${esc(p.name)} estourou</h3><p class="muted">${esc(p.name)} chegou a <b>${p.score} pontos</b> na rodada ${p.eliminatedRound}.</p><p>Se fizer a recompra, volta para <b>${highest} pontos</b>, que é a maior pontuação entre os jogadores ativos.</p><div class="actions-row"><button id="noRebuy" class="secondary">Não recomprar</button><button id="doRebuy" class="primary">Recomprar</button></div></div>`);
$("#noRebuy").onclick=showGame;$("#doRebuy").onclick=()=>{const before=p.score;p.score=highest;p.eliminated=false;p.rebuys=(p.rebuys||0)+1;p.eliminatedRound=null;g.rebuys=(g.rebuys||[]);g.rebuys.push({player:playerIndex,round:g.round,from:before,to:highest});save(g);showGame();toast(`${p.name} voltou com ${highest} pontos`)}}
function applyRound(players,round){return players.map((p,i)=>{const q={...p};if(!q.eliminated)q.score+=i===round.winner?0:(round.points[i]||0);if(q.score>=load().limit)q.eliminated=true;return q})}
function undoRound(){const g=load();if(!g.rounds.length)return;g.rounds.pop();const base=g.rounds.length?g.rounds[0].beforePlayers.map(p=>({...p,score:0,eliminated:false})):g.players.map(p=>({...p,score:0,eliminated:false}));g.players=base;for(const r of g.rounds)g.players=applyRound(g.players,r);g.round=Math.max(0,g.round-1);save(g);showGame();toast("Última rodada desfeita")}
function history(){const g=load();const eliminated=(g?.players||[]).filter(p=>p.eliminated&&p.eliminatedRound);show(`<div class="panel-title"><h2>Histórico</h2><button id="hc" class="secondary">Fechar</button></div>${g&&g.rounds.length?g.rounds.slice().reverse().map((r,rev)=>{const idx=g.rounds.length-1-rev;const names=g.players.map(p=>p.name);const estouraram=g.players.filter(p=>p.eliminatedRound===r.round);return `<div class="history-round"><div class="history-head"><b>Rodada ${r.round}</b><button class="secondary small editRound" data-i="${idx}">Editar</button></div>${estouraram.length?`<div class="elimination"><b>🔴 ${estouraram.map(p=>esc(p.name)).join(", ")} estourou${estouraram.length>1?"ram":""} nesta rodada</b><div class="muted">${estouraram.map(p=>esc(p.name)+" chegou a "+p.score+" pontos").join(" • ")}</div></div>`:""}<div class="history-body">${Object.keys(r.points).map(i=>`<div class="history-line"><span>${esc(names[i]||"Jogador")}${+i===r.winner?' <b class="green">• bateu</b>':''}</span><b>${+i===r.winner?0:r.points[i]}</b></div>`).join("")}</div></div>`}).join(""):"<p class='muted'>Nenhuma rodada registrada.</p>"}${g&&g.rebuys&&g.rebuys.length?`<div class="winner-summary"><b>🔄 Recompras</b><div class="elimination-list">${g.rebuys.slice().reverse().map(r=>`<div class="elimination-item"><span>${esc(g.players[r.player]?.name||"Jogador")} — rodada ${r.round}</span><strong>${r.from} → ${r.to} pontos</strong></div>`).join("")}</div></div>`:""}${eliminated.length?`<div class="winner-summary"><b>Eliminações</b><div class="elimination-list">${eliminated.map(p=>`<div class="elimination-item"><span>${esc(p.name)}</span><strong>Rodada ${p.eliminatedRound} • ${p.score} pontos</strong></div>`).join("")}</div></div>`:""}<div class="winner-summary"><b>🏆 Situação atual</b><p class="muted">${g&&g.players.filter(p=>!p.eliminated).length===1?esc(g.players.find(p=>!p.eliminated).name)+" é o vencedor.":g?"Partida em andamento.":"Nenhuma partida."}</p></div>`);$("#hc").onclick=closePanel;$$(".editRound").forEach(b=>b.onclick=()=>showRound(+b.dataset.i))}

function settings(){const g=load();show(`<div class="panel-title"><h2>Configurações</h2><button id="sc" class="secondary">Fechar</button></div><p class="muted">Recompra: <b>${g&&g.allowRebuy?"ativada":"desativada"}</b></p><button id="toggleRebuy" class="secondary">${g&&g.allowRebuy?"Desativar":"Ativar"} recompra</button>`);$("#sc").onclick=closePanel;$("#toggleRebuy").onclick=()=>{const x=load();x.allowRebuy=!x.allowRebuy;save(x);settings()}}
function finishGame(){const g=load();const active=g.players.filter(p=>!p.eliminated);const winner=active.length===1?active[0]:null;show(`<div class="champion finish"><div class="trophy">🏆</div><h2>${winner?esc(winner.name):"Partida finalizada"}</h2><p class="muted">${winner?`Vencedor com ${winner.score} pontos após ${g.round} rodada${g.round===1?"":"s"}.`:"A partida foi encerrada."}</p></div><button id="newAfter" class="primary">Nova partida</button><button id="closeFinish" class="secondary">Fechar</button>`);$("#newAfter").onclick=newGame;$("#closeFinish").onclick=closePanel}
$("#newGameBtn").onclick=newGame;cont.onclick=showGame;$("#historyBtn").onclick=history;$("#settingsBtn").onclick=settings;renderHome();
window.addEventListener("error",function(e){console.error("Pontinho:",e.error||e.message);});
